### ISSUE TITLE
Permission error on docker-compose up

### ISSUE THREAD

**Issue by joke2k** [PrestaShop/docker-ci#14]
I cloned develop branch of prestashop repo,
when I try to run `docker-compose up`, mysql container starts correctly, prestashop-git nope.
This is the error:

```
prestashop-git | /usr/local/bin/docker-php-entrypoint: 9: exec: /tmp/docker_run_git.sh: Permission denied
prestashop-git exited with code 126
```

**Comment by Quetzacoalt91** [comment]
Thank you for the report AND the fix :)
